var R=[
  {n:"Agriturismo Al Faggio",a:"Via Faggio 4, Schilpario, Lombardia",pl:2,pr:"€€ · ~32€",cu:"Bergamasca di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Agriturismo%20Al%20Faggio%20ristorante",st:"Agriturismo nell Alta Val di Scalve vicino a Schilpario. Cucina bergamasca di montagna: casoncelli, polenta, selvaggina e formaggi dell Orobica. Produzione propria.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L Alta Val di Scalve e una delle valli bergamasche piu integre e selvagge.","I casoncelli alla bergamasca di montagna con burro e salvia sono quelli della nonna.","I formaggi dell Orobica come il Formai de Mut DOP sono tra i migliori delle Alpi italiane."]},
  {n:"Agriturismo Malga Lunga",a:"Loc. Malga Lunga 1650m, Val Brembana, Lombardia",pl:2,pr:"€€ · ~30€",cu:"Bergamasca d'Alpeggio",tg:"italiana",ws:"https://www.google.com/search?q=Agriturismo%20Malga%20Lunga%20ristorante",st:"Malga storica a 1650 metri in Val Brembana. Formaggi prodotti in proprio: Formai de Mut DOP, taleggio e strachitunt DOP. Cucina di alpeggio: polenta con i formaggi di malga.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La malga produce il Formai de Mut DOP e lo Strachitunt DOP direttamente in alpeggio.","La polenta con i formaggi di malga freschi e uno dei piatti piu puri della cucina alpina.","Lo Strachitunt DOP e il formaggio blu piu raro d Italia: si produce solo in Val Brembana."]},
  {n:"Al Camin",a:"Via Alvera 99, Cortina d'Ampezzo, Veneto",pl:3,pr:"€€€ · ~55€",cu:"Ampezzana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Al%20Camin%20ristorante",st:"Ristorante storico di Cortina d Ampezzo. Cucina ampezzana di tradizione: canederli, goulash ampezzano, capriolo ai mirtilli, strudel di mele con panna montata. La montagna nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Al Camin e l indirizzo piu autentico di Cortina per la cucina ampezzana tradizionale.","Il capriolo ai mirtilli selvatici e il piatto piu dolomitico che si possa mangiare a Cortina.","La tradizione gastronomica ampezzana qui viene tramandata da generazioni senza adulterazioni."]},
  {n:"Al Cantinone",a:"Via Saroch 1, Madesimo, Lombardia",pl:3,pr:"€€€ · ~65€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Al%20Cantinone%20ristorante",st:"Ristorante storico di Madesimo ai piedi del Maloja. Cucina della Valchiavenna: pizzoccheri, polenta, capriolo e Bitto di Albaredo. Vista sulle piste da sci del Motta.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Madesimo e una delle stazioni sciistiche piu belle d Italia: Al Cantinone e il ristorante dei sciatori.","Il Bitto storico di Albaredo e il formaggio piu pregiato e raro delle Alpi italiane.","La polenta taragna con i funghi porcini e un piatto che si trova solo a queste latitudini."]},
  {n:"Albergo Diffuso Sauris",a:"Via Roma 1, Sauris di Sopra, Friuli",pl:3,pr:"€€€ · ~55€",cu:"Carnica Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Albergo%20Diffuso%20Sauris%20ristorante",st:"Ristorante dell Albergo Diffuso di Sauris a 1400 metri. Cucina carnica contemporanea con il prosciutto di Sauris IGP, i funghi porcini delle Carnie e i formaggi di alpeggio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["L Albergo Diffuso di Sauris e uno dei concetti ospitali piu originali d Italia.","La cucina carnica contemporanea trova qui un indirizzo di qualita nel borgo piu alto del Friuli.","Il prosciutto di Sauris affumicato con il pane di segale e la merenda piu buona delle Alpi."]},
  {n:"Alpenroyal Gourmet",a:"Strada Meisules 43, Selva di Val Gardena, Trentino",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Alpenroyal%20Gourmet%20ristorante",st:"Una stella Michelin a Selva di Val Gardena. Chef Mario Porcelli. Alta cucina alpina nell Alpenroyal Hotel con vista panoramica sulle Dolomiti dell Unesco.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Le Dolomiti Patrimonio UNESCO come sfondo: la cena piu scenografica delle Alpi italiane.","Mario Porcelli costruisce piatti che rispettano la montagna e la esaltano con grande tecnica.","L Alpenroyal e uno degli hotel piu esclusivi della Val Gardena: il ristorante e all altezza."]},
  {n:"Anna Stuben",a:"Via Rezia 1, Ortisei, Trentino",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Gardenese",tg:"italiana",ws:"https://www.google.com/search?q=Anna%20Stuben%20ristorante",st:"Una stella Michelin a Ortisei in Val Gardena. Chef Reimund Brunner. Cucina gardenese di altissimo livello nell Hotel Gardena. Canederli, Kaminwurzen e selvaggina delle Dolomiti.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Ortisei e il cuore della Val Gardena: Anna Stuben e il ristorante che la racconta meglio.","La cucina ladina di Reimund Brunner recupera ingredienti e ricette che stavano scomparendo.","La stube in legno secolare e il contesto piu autentico in cui cenare nelle Dolomiti."]},
  {n:"Atelier Moessmer",a:"Via Graben 4, Brunico, Trentino",pl:5,pr:"€€€€€ · ~280€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Atelier%20Moessmer%20ristorante",st:"Tre stelle Michelin a Brunico. Chef Norbert Niederkofler. La filosofia Cook the Mountain: solo ingredienti delle Alpi, nessun prodotto dal mare. Il ristorante piu importante delle montagne italiane.",mi:{s:3,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:19,l:"19/20"},rv:["Tre stelle Michelin e la filosofia Cook the Mountain: rivoluzionaria cucina alpina senza compromessi.","Norbert Niederkofler ha dimostrato che le Alpi possono produrre la grande cucina come il mare.","Solo ingredienti delle Dolomiti: cervo, erbe di montagna, formaggi d alpeggio. Un manifesto."]},
  {n:"Auberge de la Maison",a:"Loc. Entreves 16, Courmayeur, Piemonte",pl:4,pr:"€€€€ · ~90€",cu:"Valdostana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Auberge%20de%20la%20Maison%20ristorante",st:"Ristorante ad Entreves ai piedi del Monte Bianco. Chef Paolo Vai. Cucina valdostana d autore con ingredienti del Monte Bianco: fonduta, carbonade, lardo di Arnad.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Il Monte Bianco come sfondo: la cucina valdostana qui raggiunge il suo livello piu alto.","La fonduta valdostana con il fontina DOP e la carbonade sono i piatti simbolo della Valle.","Courmayeur e la localita di montagna piu elegante d Italia: l Auberge ne e il ristorante piu bello."]},
  {n:"Baita La Piazzola",a:"Loc. Passo del Tonale 1900m, Ponte di Legno, Lombardia",pl:2,pr:"€€ · ~38€",cu:"Adamellina di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Baita%20La%20Piazzola%20ristorante",st:"Baita al Passo del Tonale con vista sul Ghiacciaio del Presena e sulla Presanella. Cucina di montagna bresciana: polenta concia, goulash, strudel. Al confine tra Lombardia e Trentino.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Passo del Tonale e uno dei valichi piu spettacolari delle Alpi: ghiacciaio e panorama.","La polenta concia al Passo del Tonale con i formaggi di malga e perfetta dopo le piste.","Al confine tra Lombardia e Trentino: la cucina assorbe le tradizioni di entrambe le regioni."]},
  {n:"Baita Plan dei Spini",a:"Loc. Plan dei Spini 1900m, Ponte di Legno, Lombardia",pl:2,pr:"€€ · ~38€",cu:"Bresciana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Baita%20Plan%20dei%20Spini%20ristorante",st:"Baita a 1900 metri a Ponte di Legno con vista sul Ghiacciaio del Presena. Cucina bresciana di montagna: polenta, selvaggina, formaggi dell Adamello. La natura nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Ghiacciaio del Presena e uno dei piu spettacolari delle Alpi: la baita vi si trova sotto.","La polenta con la selvaggina dell Adamello e il pasto piu montanaro della Lombardia.","Ponte di Legno e la stazione sciistica bresciana piu alta: cucina di montagna autentica."]},
  {n:"Castel Fine Dining",a:"Via Labers 4, Merano, Trentino",pl:5,pr:"€€€€€ · ~190€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Castel%20Fine%20Dining%20ristorante",st:"Due stelle Michelin a Merano nel castello medievale. Chef Gerhard Wieser. Cucina altoatesina di altissimo livello in uno dei castelli piu belli dell Alto Adige.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin in un castello medievale: la location e gia un capolavoro.","Gerhard Wieser porta la cucina altoatesina a livelli di raffinatezza internazionale.","La cantina del castello con le grandi annate sudtirolesi e un tesoro da non perdere."]},
  {n:"Contrada Bricconi",a:"Loc. Bricconi, Oltressenda Alta, Lombardia",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Contrada%20Bricconi%20ristorante",st:"Tre Forchette Gambero Rosso 2026 in un borgo del XV secolo sulle montagne bergamasche. Allevamento proprio, formaggi di malga, cucina di montagna di grandissima qualita e identita.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Un borgo del XV secolo recuperato e trasformato in ristorante di montagna: visionario e bellissimo.","Gli animali vengono allevati nel borgo e i formaggi prodotti in proprio: km zero assoluto.","Tre Forchette Gambero Rosso 2026: la conferma che la cucina di montagna bergamasca e la migliore d Italia."]},
  {n:"DaGorini",a:"Via Giovanni Pascoli 1, Bagno di Romagna, Emilia Romagna",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Appenninica",tg:"italiana",ws:"https://www.google.com/search?q=DaGorini%20ristorante",st:"Tre Forchette Gambero Rosso 2026 nell Appennino tosco-emiliano. Chef Gianluca Gorini. Cucina di montagna appenninica con ingredienti del Parco Nazionale delle Foreste Casentinesi.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Tre Forchette Gambero Rosso: la cucina appenninica di Gorini e tra le piu originali d Italia.","Il Parco Nazionale delle Foreste Casentinesi fornisce ingredienti rarissimi: erbe, funghi, selvaggina.","Bagno di Romagna e fuori dai circuiti: ci si va apposta per questa cucina straordinaria."]},
  {n:"Dolomieu",a:"Via Cima Tosa 5, Madonna di Campiglio, Trentino",pl:5,pr:"€€€€€ · ~160€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Dolomieu%20ristorante",st:"Una stella Michelin al DV Chalet di Madonna di Campiglio. Chef Fiorenzo Perremuto. Stube in legno antico con cucina che profuma di terra, mare e montagna.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La stube in legno antico del DV Chalet e una delle piu belle delle Dolomiti.","Fiorenzo Perremuto costruisce piatti che uniscono la montagna al mare con grande eleganza.","Madonna di Campiglio e lo skyline delle Dolomiti come sfondo: la cena piu bella delle Alpi."]},
  {n:"El Molin",a:"Via Dossi 1, Cavalese, Trentino",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Trentina",tg:"italiana",ws:"https://www.google.com/search?q=El%20Molin%20ristorante",st:"Una stella Michelin a Cavalese in Val di Fiemme. Chef Alessandro Gilmozzi. Cucina trentina di ricerca con erbe di montagna, funghi e selvaggina. La natura delle Dolomiti nel piatto.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Alessandro Gilmozzi e il pioniere delle erbe di montagna in cucina: raccolta e ricerca costante.","La Val di Fiemme in inverno e estate fornisce ingredienti che nessun altro chef conosce cosi bene.","La cantina con i Trentin DOC e Nosiola e una delle piu rappresentative del territorio."]},
  {n:"Grual",a:"Via Genova 22, Pinzolo, Trentino",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Trentina",tg:"italiana",ws:"https://www.google.com/search?q=Grual%20ristorante",st:"Una stella Michelin a Pinzolo in Val Rendena. Chef Roberto Sacchet. Cucina trentina contemporanea ai piedi delle Dolomiti di Brenta. Funghi, capriolo e formaggi di alpeggio della Val Rendena.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Pinzolo e la porta delle Dolomiti di Brenta: Grual e il ristorante gourmet di riferimento.","Chef Sacchet racconta la Val Rendena con ingredienti di eccellenza e tecnica contemporanea.","La selvaggina e i funghi della val Rendena sono ingredienti di qualita che non si trovano altrove."]},
  {n:"Il Cantinone e Sport Hotel Alpina",a:"Via Carducci 19, Madesimo, Lombardia",pl:3,pr:"€€€ · ~60€",cu:"Valchiavennasca Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Cantinone%20e%20Sport%20Hotel%20Alpina%20ristorante",st:"Ristorante storico di Madesimo. Cucina della Valchiavenna: pizzoccheri, polenta, capriolo e Bitto Storico di Albaredo. Ai piedi delle piste della Motta.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Madesimo e una delle stazioni sciistiche piu belle d Italia: il ristorante e il cuore del paese.","Il Bitto Storico di Albaredo e il formaggio piu raro e pregiato delle Alpi italiane.","La polenta taragna con il Bitto e un abbinamento che si trova solo in queste valli."]},
  {n:"Il Gallo Cedrone",a:"Via Cima Tosa 80, Madonna di Campiglio, Trentino",pl:5,pr:"€€€€€ · ~140€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Gallo%20Cedrone%20ristorante",st:"Una stella Michelin all Hotel Bertelli di Madonna di Campiglio. Chef Sabino Fortunato. Cucina che unisce i sapori mediterranei dello chef campano con la tradizione alpina trentina.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Un incontro tra il Mediterraneo e le Alpi: lo chef campano a Madonna di Campiglio funziona.","I tortellini con la mortandela della Val di Non in consomme di cappone sono il piatto simbolo.","La cucina di montagna vista dal Sud: un punto di vista originale che arricchisce la tradizione."]},
  {n:"Kuppelrain",a:"Via Senales 2, Castelbello, Trentino",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Kuppelrain%20ristorante",st:"Una stella Michelin a Castelbello in Val Venosta. Chef Jorg Trafoier. Cucina alpina di territorio con ingredienti della Val Venosta: grano saraceno, mele, Vinschger Marille.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La Val Venosta e il territorio agricolo piu integro dell Alto Adige: Kuppelrain lo racconta.","Il grano saraceno e le mele della Val Venosta sono gli ingredienti piu identitari di questa cucina.","Jorg Trafoier e uno dei custodi piu importanti della tradizione gastronomica alpina."]},
  {n:"L'Argine a Vencò",a:"Loc. Vencò 15, Dolegna del Collio, Friuli",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina del Collio",tg:"italiana",ws:"https://www.google.com/search?q=L'Argine%20a%20Venc%C3%B2%20ristorante",st:"Tre Forchette Gambero Rosso 2026 a Dolegna del Collio. Chef Antonia Klugmann. Cucina di confine tra Italia e Slovenia con erbe spontanee, formaggi del Collio e vini biologici.",mi:{s:0,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Antonia Klugmann e la chef friulana piu conosciuta: cucina di confine di grande originalita.","Le erbe spontanee del Collio sono la base di una cucina vegetale autentica e coraggiosa.","Il Collio-Brda tra Italia e Slovenia e il territorio gastronomico piu unico d Italia."]},
  {n:"La Meiro",a:"Via Castello 2, Acceglio, Piemonte",pl:2,pr:"€€ · ~35€",cu:"Occitana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=La%20Meiro%20ristorante",st:"Agriturismo in alta Valle Maira, la valle delle meraviglie alpine piemontesi. Cucina occitana autentica: ravioles, capriolo, funghi e Saras del fen, il formaggio piu antico delle Alpi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Valle Maira e la piu bella delle valli occitane del Piemonte: paesaggi alpini intatti.","Il Saras del fen e il formaggio piu antico delle Alpi: avvolto nel fieno, sapore unico.","I ravioles di patate con la toma d alpeggio sono il piatto simbolo della cucina occitana."]},
  {n:"La Stua de Michil",a:"Str. Col Alt 105, Corvara in Badia, Trentino",pl:4,pr:"€€€€ · ~95€",cu:"Alta Cucina Ladina",tg:"italiana",ws:"https://www.google.com/search?q=La%20Stua%20de%20Michil%20ristorante",st:"Una stella Michelin a Corvara in Alta Badia. Chef Simone Cantafio. Cucina ladina contemporanea nella stube storica del Hotel La Perla. Canederli, casunziei e selvaggina dell Alta Badia.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Corvara e il cuore dell Alta Badia: La Stua de Michil e l anima gastronomica del paese.","La cucina ladina di Cantafio valorizza una cultura gastronomica rarissima e in via di scomparsa.","La stube storica del Hotel La Perla e uno dei contesti piu intimi e caldi delle Dolomiti."]},
  {n:"La Subida",a:"Via Subida 52, Cormons, Friuli",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Friulana",tg:"italiana",ws:"https://www.google.com/search?q=La%20Subida%20ristorante",st:"Una stella Michelin a Cormons nel Collio. Chef Mitja Sirk. Cucina friulana contemporanea con ingredienti del Carso e del Collio: Montasio, prosciutto di San Daniele, erbe spontanee.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Una stella Michelin nel Collio: Mitja Sirk racconta il Friuli con una cucina di grande identita.","La subida e un agriturismo di lusso: si arriva e non si vuole piu andare via.","Il Collio con Slovenia davanti e il territorio gastronomico piu originale d Italia."]},
  {n:"Lemin",a:"Via Statale 13, Piatta di Teglio, Lombardia",pl:3,pr:"€€€ · ~60€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Lemin%20ristorante",st:"Trattoria valtellinese autentica a Teglio, il paese dei pizzoccheri. Cucina della Valtellina: pizzoccheri della tradizione, bresaola della Valtellina, Sciatt. Il territorio nel piatto.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Teglio e il paese dei pizzoccheri: la ricetta originale del pizzocchero IGP viene da qui.","I pizzoccheri di Teglio con il formaggio Casera di Valtellina sono il piatto piu identitario della Lombardia montana.","La bresaola della Valtellina IGP e lo Sciatt sono qui nella loro versione piu autentica."]},
  {n:"Lo Chalet",a:"Via Cesana 6, Sestriere, Piemonte",pl:3,pr:"€€€ · ~55€",cu:"Piemontese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Lo%20Chalet%20ristorante",st:"Ristorante storico di Sestriere, stazione olimpica delle Alpi. Cucina piemontese di montagna: selvaggina, fonduta, polenta concia. La cucina gourmet della via Lattea.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Sestriere ospito le Olimpiadi 2006: Lo Chalet e il ristorante storico della stazione olimpica.","La fonduta piemontese con il fontina valdostano e la scelta giusta dopo una giornata di sci.","La Via Lattea con 400 km di piste ha in Lo Chalet un punto gastronomico di riferimento."]},
  {n:"Locanda Margon",a:"Via Margone 15, Ravina, Trentino",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Trentina",tg:"italiana",ws:"https://www.google.com/search?q=Locanda%20Margon%20ristorante",st:"Una stella Michelin a Ravina, nelle cantine Lunelli di Ferrari Spumante. Chef Edoardo Fumagalli. Cucina trentina d autore in una villa del 700 circondata dai vigneti del Trentino.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["Nelle cantine Ferrari Spumante: la miglior bolliicina d Italia come benvenuto e compagnia di cena.","Chef Fumagalli racconta il Trentino con ingredienti locali di eccellenza e tecnica moderna.","La villa del 700 tra i vigneti con le Dolomiti sullo sfondo: location di rara bellezza."]},
  {n:"Malga Panna",a:"Via Costalunga 29, Moena, Trentino",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Trentina",tg:"italiana",ws:"https://www.google.com/search?q=Malga%20Panna%20ristorante",st:"Una stella Michelin a Moena in Val di Fassa. Chef Paolo Donei dal 1993, il piu giovane stellato d Italia all epoca. Cucina che parla trentino: speck, canederli, capriolo e formaggi d alpeggio.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Paolo Donei stellato dal 1993 a 19 anni: il piu longevo chef stellato del Trentino Alto Adige.","La cucina che parla trentino non ha mai ceduto alle mode: coerenza e profondita rara.","I canederli di malga con lo speck della Val di Fassa sono il piatto piu emozionante del menu."]},
  {n:"Maso Franch",a:"Loc. Franch 5, Giovo, Trentino",pl:3,pr:"€€€ · ~60€",cu:"Trentina di Campagna",tg:"italiana",ws:"https://www.google.com/search?q=Maso%20Franch%20ristorante",st:"Agriturismo di qualita nella Valle di Cembra. Cucina trentina di maso autentica: funghi della valle, canederli, capriolo e Muller Thurgau di Cembra. La vita di maso nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il maso trentino e il luogo dove la cucina di montagna conserva la sua anima piu vera.","I funghi della Valle di Cembra e il capriolo dell Adamello sono ingredienti rarissimi.","Il Muller Thurgau di Cembra e il vino piu fresco e floreale del Trentino: abbinamento perfetto."]},
  {n:"Osteria a Le Due Spade",a:"Via Don Arcangelo Rizzi 11, Trento, Trentino",pl:3,pr:"€€€ · ~60€",cu:"Trentina Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20a%20Le%20Due%20Spade%20ristorante",st:"Ristorante storico di Trento dal 1545. Cucina trentina autentica: carne salada, strangolapreti, smalz trentino. Cantina con i migliori Trentino DOC e Teroldego Rotaliano.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dal 1545: il ristorante piu antico di Trento e tra i piu storici del Trentino.","La carne salada trentina e lo strangolapreti sono eseguiti secondo la tradizione immutata.","La cantina con il Teroldego Rotaliano e il Marzemino e un viaggio nei vini piu originali d Italia."]},
  {n:"Osteria Ai Cacciatori",a:"Via Nazionale 22, Auronzo di Cadore, Veneto",pl:2,pr:"€€ · ~36€",cu:"Cadorina di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20Ai%20Cacciatori%20ristorante",st:"Osteria storica di Auronzo di Cadore vicino alle Tre Cime di Lavaredo. Cucina cadorina: strangolapreti, goulash, capriolo, funghi e formaggi di malga.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le Tre Cime di Lavaredo sono visibili da Auronzo: la cucina cadorina ha questo sfondo.","Gli strangolapreti con burro e salvia sono il piatto piu semplice e delizioso delle Dolomiti.","Il capriolo del Comelico e il fungo porcino del Cadore sono materia prima di eccellenza."]},
  {n:"Osteria al Castello",a:"Via al Castello 1, Crissolo, Piemonte",pl:2,pr:"€€ · ~35€",cu:"Cuneese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20al%20Castello%20ristorante",st:"Osteria ai piedi del Monviso in Valle Po. Cucina cuneese di montagna: trota del Po, capriolo, polenta. Il Re di Pietra come sfondo di ogni piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Monviso, il Re di Pietra, e il monumento piu bello delle Alpi piemontesi.","La trota del Po nasce qui: a Crissolo il Po e un ruscello di montagna cristallino.","Cucina di montagna povera e ricca allo stesso tempo: semplicita e qualita degli ingredienti."]},
  {n:"Osteria Altran",a:"Loc. Altan 31, San Quirino, Friuli",pl:2,pr:"€€ · ~36€",cu:"Friulana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20Altran%20ristorante",st:"Osteria storica a San Quirino nelle Prealpi Pordenonesi. Cucina friulana autentica: cjarsons di Forni di Sopra, frico di Carnia, agnello delle Dolomiti Friulane.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I cjarsons di Forni di Sopra sono i piu elaborati del Friuli: dolce-salati con ingredienti di montagna.","L agnello delle Dolomiti Friulane e di una qualita eccezionale: pascola libero ad alta quota.","Le Prealpi Pordenonesi sono il territorio piu selvaggio e intatto del Friuli."]},
  {n:"Osteria degli Alpini",a:"Via Nazionale 18, Valdidentro, Lombardia",pl:2,pr:"€€ · ~35€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20degli%20Alpini%20ristorante",st:"Trattoria storica a Valdidentro in Alta Valtellina vicino a Bormio. Cucina valtellinese autentica: pizzoccheri, polenta taragna, sciatt, bresaola e Valtellina Superiore.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Valdidentro e in Alta Valtellina a due passi da Bormio: cucina di alta montagna autentica.","Gli sciatt, le frittelle di grano saraceno con il formaggio, sono una sosta obbligatoria.","La bresaola della Valtellina DOP qui e quella artigianale: sapore di montagna inconfondibile."]},
  {n:"Osteria del Rifugio",a:"Via al Rifugio 1, Aprica, Lombardia",pl:2,pr:"€€ · ~35€",cu:"Valtellinese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20del%20Rifugio%20ristorante",st:"Osteria di montagna ad Aprica. Cucina valtellinese: pizzoccheri, bresaola, sciatt e Valtellina Superiore. Una delle stazioni sciistiche piu tranquille della Valtellina.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Aprica e tra Valtellina e Valcamonica: la cucina assorbe il meglio di entrambe le tradizioni.","I pizzoccheri di Aprica con il Casera stagionato sono nella versione autentica della valtellinese.","La bresaola artigianale di Aprica e quella meno industriale della Valtellina."]},
  {n:"Osteria dell'Enoteca",a:"Via Roma 12, Livigno, Lombardia",pl:2,pr:"€€ · ~40€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20dell'Enoteca%20ristorante",st:"Osteria tradizionale a Livigno, il paese duty free delle Alpi. Cucina livignasca autentica: polenta, selvaggina, funghi e Sforzato di Valtellina. Il territorio di confine nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Livigno e il paradiso dello sci e dello shopping duty-free: l osteria e il rifugio gastronomico.","La cucina livignasca ha influenze svizzere e valtellinesi: un mix unico nella montagna alpina.","Il cinghiale e il capriolo cacciati nelle foreste di Livigno sono gli ingredienti piu pregiati."]},
  {n:"Osteria della Piazza",a:"Via Roma 4, Pievepelago, Emilia Romagna",pl:2,pr:"€€ · ~35€",cu:"Modenese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20della%20Piazza%20ristorante",st:"Osteria storica a Pievepelago nell Appennino modenese, porta del Cimone. Cucina modenese di montagna: gnocco fritto, tigelle, tortellini di patate, cinghiale in umido.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Pievepelago e la porta del Monte Cimone, il punto piu alto dell Appennino settentrionale.","Il gnocco fritto con il culatello modenese e uno degli antipasti piu buoni dell Appennino.","I tortellini di patate modenesi sono diversi da quelli di carne: un piatto povero di grande sapore."]},
  {n:"Osteria La Gjalina",a:"Via Roma 3, Sutrio, Friuli",pl:2,pr:"€€ · ~34€",cu:"Carnica Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20La%20Gjalina%20ristorante",st:"Osteria tradizionale a Sutrio, il paese delle maschere di legno. Cucina carnica: cjarsons, frico morbido, polenta e funghi delle Carnie. Il Carnevale e la cucina di montagna nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Sutrio e famosa per le maschere di legno: la cucina carnica e parte dello stesso universo di tradizioni.","Il frico morbido con le patate e il formaggio Montasio e il piatto piu confortante del Friuli.","I cjarsons dolce-salati di Sutrio hanno una ricetta unica: ogni paese della Carnia ha la sua."]},
  {n:"Osteria La Rocca",a:"Via Maestra 1, Montefiorino, Emilia Romagna",pl:2,pr:"€€ · ~33€",cu:"Modenese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20La%20Rocca%20ristorante",st:"Osteria nell Appennino modenese a Montefiorino, borgo della Resistenza. Cucina di montagna: tigelle con squacquerone, cinghiale alla modenese, castagne arrosto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Montefiorino e il borgo della Resistenza partigiana: cucina e storia in un unico posto.","Le tigelle con lo squacquerone e il lardo sono la merenda piu buona dell Appennino modenese.","Le castagne di Montefiorino arrosto sono il dolce naturale delle foreste appenniniche."]},
  {n:"Osteria Senterej",a:"Via Stelvio 7, Bormio, Lombardia",pl:2,pr:"€€ · ~38€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20Senterej%20ristorante",st:"Osteria storica di Bormio. Cucina valtellinese autentica: pizzoccheri, polenta taragna, capriolo alla valtellinese, Sforzato di Valtellina. L osteria piu autentica delle Alpi lombarde.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Bormio e la capitale della Valtellina: Senterej e l osteria che la racconta con piu onesta.","La polenta taragna con il formai de mut e un piatto che riscalda corpo e anima.","Lo Sforzato di Valtellina DOCG con il capriolo e l abbinamento piu alto della cucina montana."]},
  {n:"Osteria Vecchio Mulino",a:"Via Nazionale 74, Venasca, Piemonte",pl:2,pr:"€€ · ~38€",cu:"Occitana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20Vecchio%20Mulino%20ristorante",st:"Osteria storica nell Valle Varaita, area occitana delle Alpi Piemontesi. Cucina cuneese di montagna: capriolo, cinghiale, funghi porcini delle Alpi Marittime e ravioles occitani.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Valle Varaita e il cuore dell area occitana piemontese: cucina di montagna con identita rara.","I ravioles occitani con burro di alpeggio sono il piatto piu identitario di queste valli.","Il capriolo delle Alpi Marittime e di una qualita eccezionale: pascola libero ad alta quota."]},
  {n:"Porcino",a:"Via Pareda 32, Badia, Trentino",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Porcino%20ristorante",st:"Nuova stella Michelin 2026 a Badia in Alta Badia. Chef Marco Verginer. Cucina alpina contemporanea al Badia Hill Hotel con vista sulle Dolomiti dell Alta Badia.",mi:{s:1,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:15,l:"15/20"},rv:["Nuova stella Michelin 2026 in Alta Badia: Marco Verginer porta una visione originale.","L Alta Badia e la valle piu gourmet delle Dolomiti: Porcino ne e la new entry piu eccitante.","La vista sull Alta Badia e sulle Dolomiti patrimonio UNESCO e di una bellezza assoluta."]},
  {n:"Quellenhof Gourmetstube 1897",a:"Via San Zeno 38, San Martino in Passiria, Trentino",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Quellenhof%20Gourmetstube%201897%20ristorante",st:"Nuova stella Michelin 2026 a San Martino in Passiria. Chef Michael Mayr. Cucina altoatesina gourmet nel lussuoso resort Quellenhof con piscine termali e giardini.",mi:{s:1,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:15,l:"15/20"},rv:["Nuova stella 2026 al Quellenhof: uno dei resort piu lussuosi dell Alto Adige premia la cucina.","Michael Mayr porta una cucina altoatesina fresca e contemporanea al resort termale.","La combinazione di terme, natura e cucina stellata e quella tipica del lusso altoatesino."]},
  {n:"Reale",a:"Viale L. De Renzis Sonnante 1, Castel di Sangro, Abruzzo",pl:5,pr:"€€€€€ · ~280€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Reale%20ristorante",st:"Tre stelle Michelin a Castel di Sangro. Chef Nino Di Costanzo. La cucina di montagna appenninica piu importante d Italia: erbe del Parco Nazionale d Abruzzo, agnello, funghi e tartufo nero.",mi:{s:3,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:20,l:"20/20"},rv:["Tre stelle Michelin a Castel di Sangro: il punto piu alto della cucina italiana di montagna appenninica.","Nino Di Costanzo racconta l Appennino abruzzese con una cucina di profondita assoluta.","Il tartufo nero di Norcia e l agnello degli Appennini sono ingredienti che non hanno rivali."]},
  {n:"Reale Casadonna",a:"Loc. Casadonna, Castel di Sangro, Abruzzo",pl:3,pr:"€€€ · ~65€",cu:"Abruzzese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Reale%20Casadonna%20ristorante",st:"L osteria del gruppo Reale di Nino Di Costanzo a Castel di Sangro. Cucina abruzzese popolare di altissima qualita: maccheroni alla chitarra, arrosticini, agnello del Parco d Abruzzo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["L osteria del tre stelle Michelin: qualita di Reale a prezzi accessibili.","Gli arrosticini di pecora abruzzese qui sono quelli di qualita eccezionale: lenti e profumati.","Il maccherone alla chitarra con il ragu di agnello e il piatto piu abruzzese del menu."]},
  {n:"Rifugio Albani",a:"Loc. Alpe Brunone 1935m, Valbondione, Lombardia",pl:1,pr:"€ · ~22€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Albani%20ristorante",st:"Rifugio a 1935 metri nel Parco delle Orobie a Valbondione. Cucina di rifugio bergamasca: polenta e formaggio, minestrone di verdure di stagione, selvaggina.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Parco delle Orobie Bergamasche e il cuore selvaggio delle Alpi lombarde.","La polenta con il Formai de Mut DOP di alpeggio a 1935 metri: la montagna nel bicchiere.","Un rifugio vero dove si mangiano i sapori autentici della cucina alpina bergamasca."]},
  {n:"Rifugio Balma",a:"Loc. Balma 1700m, Bielmonte, Piemonte",pl:1,pr:"€ · ~25€",cu:"Biellese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Balma%20ristorante",st:"Rifugio a Bielmonte nell Oasi Zegna, paradiso naturale voluto dalla famiglia Zegna. Cucina biellese di montagna: polenta, tome e funghi delle Alpi biellesi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["L Oasi Zegna e un paradiso naturale di 100 kmq voluto da Ermenegildo Zegna: natura e cucina.","I funghi porcini delle Alpi biellesi sono tra i piu profumati d Italia.","La polenta con la toma biellese e il piatto di montagna piemontese nella sua forma piu pura."]},
  {n:"Rifugio Battisti",a:"Loc. Rifugio Battisti 1869m, Sestola, Emilia Romagna",pl:1,pr:"€ · ~20€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Battisti%20ristorante",st:"Rifugio sul Monte Cimone a 1869 metri. Il tetto dell Appennino settentrionale. Cucina di rifugio modenese: pasta al sugo, polenta, castagne. Vista sulla pianura padana.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Monte Cimone e il punto piu alto dell Appennino settentrionale: vista unica sulla pianura.","La pasta al sugo di cinghiale a 1869 metri e uno dei pasti piu soddisfacenti d Italia.","Le castagne dell Appennino modenese sono tra le piu grandi e saporite d Italia."]},
  {n:"Rifugio Città di Fiume",a:"Loc. Punta Penia 3343m, Marmolada, Veneto",pl:1,pr:"€ · ~18€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Citt%C3%A0%20di%20Fiume%20ristorante",st:"Rifugio sulla Marmolada, la Regina delle Dolomiti a 3343 metri. Cucina di alta montagna: minestrone, spezzatino, polenta. Il punto piu alto delle Dolomiti UNESCO.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A 3343 metri sulla Marmolada: il punto piu alto delle Dolomiti UNESCO.","La minestra calda sulla Regina delle Dolomiti e il cibo piu emozionante d Italia.","La Marmolada con il suo ghiacciaio e un monumento: mangiare qui e un esperienza unica."]},
  {n:"Rifugio Giaf",a:"Loc. Giaf 1400m, Forni di Sopra, Friuli",pl:1,pr:"€ · ~20€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Giaf%20ristorante",st:"Rifugio a 1400 metri in Carnia nei pressi di Forni di Sopra. Cucina carnica di rifugio: polenta, frico, cjarsons in brodo. La montagna friulana nella sua dimensione piu pura.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A 1400 metri nella Carnia friulana: la cucina di rifugio qui ha una qualita rara.","I cjarsons in brodo sono il comfort food della montagna friulana: dolci, salati e profumati.","Il frico croccante al rifugio dopo una camminata tra i larici carnici e un rito gastronomico."]},
  {n:"Rifugio Lagazuoi",a:"Passo Falzarego, Cortina d'Ampezzo, Veneto",pl:2,pr:"€€ · ~35€",cu:"Ampezzana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Lagazuoi%20ristorante",st:"Il rifugio piu bello delle Dolomiti a 2752 metri sul Passo Falzarego. Cucina ampezzana tradizionale: canederli in brodo, goulash, strudel di mele. Vista sulle Dolomiti a 360 gradi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A 2752 metri di quota: i canederli in brodo con le Dolomiti intorno sono un esperienza irripetibile.","Il Passo Falzarego e la Grande Guerra: cenare qui e un momento di storia e di bellezza.","Il rifugio piu bello delle Dolomiti: la cucina ampezzana qui raggiunge la sua dimensione piu autentica."]},
  {n:"Rifugio Quintino Sella",a:"Loc. Quintino Sella 3585m, Biella, Piemonte",pl:1,pr:"€ · ~20€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Quintino%20Sella%20ristorante",st:"Rifugio alpino sul Monte Rosa a 3585 metri. Cucina di alta montagna: minestrone, polenta, spezzatino. Il punto gastronomico piu alto del Piemonte con vista sul Monte Rosa.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A 3585 metri il piatto piu semplice diventa indimenticabile: il contesto vale tutto.","Il Monte Rosa come sfondo durante il pasto: la vista piu alta della cucina piemontese.","Cucina di rifugio autentica: polenta, spezzatino e galore per chi arriva dopo ore di salita."]},
  {n:"Ristorante 1997",a:"Via Nazionale 9, Aprica, Lombardia",pl:3,pr:"€€€ · ~55€",cu:"Valtellinese Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%201997%20ristorante",st:"Ristorante di cucina valtellinese contemporanea ad Aprica. Pizzoccheri e bresaola in chiave moderna, selvaggina e funghi delle Orobie. La montagna orobica nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Aprica e tra le stazioni sciistiche piu belle della Valtellina: il ristorante ne e il riferimento.","La cucina valtellinese contemporanea qui trova un equilibrio riuscito tra rispetto e innovazione.","I funghi delle Orobie e il capriolo dell Adamello sono la materia prima piu pregiata."]},
  {n:"Ristorante Alle Alpi",a:"Via Roma 30, Falcade, Veneto",pl:2,pr:"€€ · ~38€",cu:"Agordina di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Alle%20Alpi%20ristorante",st:"Trattoria storica a Falcade in Val Biois. Cucina agordina di montagna: casunziei ampezzani, goulash, polenta concia e formaggi delle Dolomiti Bellunesi.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Val Biois e una delle valli piu silenziose e integre delle Dolomiti.","I casunziei ampezzani con burro fuso e papavero sono il piatto simbolo delle Dolomiti venete.","Falcade e famosa per il cioccolato Elah: il dessert e qui nella sua versione originale."]},
  {n:"Ristorante Boscone",a:"Via Boscone 1, Edolo, Lombardia",pl:2,pr:"€€ · ~36€",cu:"Camonica di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Boscone%20ristorante",st:"Ristorante in Valle Camonica, la valle dei petroglifi UNESCO. Cucina camonica: spiedo bresciano, polenta, carne salada, funghi dell Adamello. Il territorio dei pastori nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Valle Camonica ha i petroglifi UNESCO piu importanti d Europa: cucina e storia.","Lo spiedo bresciano e la carne salada della Valle Camonica sono piatti che non si trovano altrove.","I funghi porcini dell Adamello crescono nei boschi di abete piu puliti d Italia."]},
  {n:"Ristorante del Lago",a:"Via Roma 1, Ceresole Reale, Piemonte",pl:2,pr:"€€ · ~40€",cu:"Montagna Piemontese",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20del%20Lago%20ristorante",st:"Ristorante sul Lago di Ceresole nel Parco Nazionale del Gran Paradiso. Cucina piemontese di montagna con selvaggina e formaggi dell alpeggio della Val Orco.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Parco Nazionale del Gran Paradiso e il piu antico d Italia: la cucina ne riflette la pulizia.","Il Lago di Ceresole Reale e uno dei piu belli delle Alpi piemontesi: contesto mozzafiato.","Lo stambecco della Val Orco si vede dalla finestra: una cucina nel cuore delle Alpi."]},
  {n:"Ristorante del Parco",a:"Via Nazionale 12, Valdieri, Piemonte",pl:2,pr:"€€ · ~38€",cu:"Cuneese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20del%20Parco%20ristorante",st:"Ristorante nel Parco Naturale delle Alpi Marittime a Valdieri. Cucina cuneese con gli ingredienti delle Alpi Marittime: capriolo, funghi, lavanda e formaggi d alpeggio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Parco delle Alpi Marittime confina con la Francia: cucina di montagna con tocchi occitani.","La lavanda delle Alpi Marittime e un ingrediente insolito in cucina: profumo delicato e unico.","Il capriolo e il camoscio del parco sono i prodotti piu pregiati di queste montagne."]},
  {n:"Ristorante Dolada",a:"Via Dolada 21, Pieve d'Alpago, Veneto",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Alpina Veneta",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Dolada%20ristorante",st:"Una stella Michelin a Pieve d Alpago sulle Prealpi Venete. Chef Riccardo De Prà. Cucina veneta di montagna con ingredienti delle Dolomiti: funghi, erbe spontanee, selvaggina.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Una stella Michelin sulle Prealpi Venete: cucina di montagna di grande profondita e identita.","Riccardo De Prà usa le erbe spontanee del bosco con una conoscenza enciclopedica.","Il Lago di Santa Croce sotto e le Dolomiti sopra: la vista di Pieve d Alpago e impareggiabile."]},
  {n:"Ristorante Enoteca di Cormons",a:"Piazza XXIV Maggio 21, Cormons, Friuli",pl:3,pr:"€€€ · ~55€",cu:"Friulana del Collio",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Enoteca%20di%20Cormons%20ristorante",st:"Enoteca e ristorante nel cuore del Collio a Cormons. Cucina friulana con i vini del Collio: abbinamenti perfetti tra la cucina di confine e i grandi bianchi friulani.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il Collio produce i bianchi piu complessi d Italia: l enoteca li racconta meglio di qualsiasi guida.","La cucina di confine tra Friuli e Slovenia e la piu originale e meno conosciuta d Italia.","Cormons e la capitale enogastronomica del Collio: l enoteca ne e il cuore pulsante."]},
  {n:"Ristorante il Pescatore",a:"Via del Lago 12, Scanno, Abruzzo",pl:2,pr:"€€ · ~35€",cu:"Abruzzese di Lago",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20il%20Pescatore%20ristorante",st:"Ristorante sul Lago di Scanno, il lago piu romantico d Abruzzo. Cucina di lago abruzzese: trota del Sagittario, carpe del lago di Scanno, polenta. Il paese dei poeti di montagna.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il Lago di Scanno e il lago piu romantico d Abruzzo e uno dei piu belli d Italia.","La trota del Sagittario e la carpa del lago di Scanno sono prodotti di acque purissime.","Scanno e il paese dei poeti abruzzesi: cucina, tradizione e poesia si intrecciano."]},
  {n:"Ristorante La Baita",a:"Via Roma 8, Limone Piemonte, Piemonte",pl:2,pr:"€€ · ~38€",cu:"Cuneese di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20La%20Baita%20ristorante",st:"Trattoria storica a Limone Piemonte, stazione sciistica delle Alpi Marittime. Cucina cuneese di montagna: capriolo, polenta, funghi e formaggi del Cuneese.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Limone Piemonte e la stazione sciistica piu vicina al mare: le Alpi Marittime sono uniche.","La cucina cuneese di montagna qui e quella autentica: capriolo e polenta senza fronzoli.","I formaggi del Cuneese come la Toma Piemontese DOP sono tra i migliori d Italia."]},
  {n:"Ristorante La Bandiera",a:"Contrada Pastini 4, Civitella Casanova, Abruzzo",pl:4,pr:"€€€€ · ~85€",cu:"Alta Cucina Abruzzese",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20La%20Bandiera%20ristorante",st:"Una stella Michelin a Civitella Casanova in Abruzzo. Chef Marcello e Bruna Spadone. Cucina abruzzese contemporanea con gli ingredienti del territorio pescarese: tartufo, agnello, formaggi.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Una stella Michelin in un paesino abruzzese: la cucina di qualita non ha confini geografici.","Marcello e Bruna Spadone portano la cucina abruzzese di montagna a livelli di alta cucina.","Il tartufo nero di Civitella Casanova e uno dei piu profumati d Abruzzo."]},
  {n:"Ristorante Mas del Saro",a:"Loc. Mas del Saro, Sappada, Veneto",pl:3,pr:"€€€ · ~60€",cu:"Sappadina di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Mas%20del%20Saro%20ristorante",st:"Ristorante a Sappada, borgo alpino di lingua tedesca nelle Dolomiti Bellunesi. Cucina sappadina: schlutzkrapfen, knoedel, goulash e formaggi del Comelico. La lingua tedesca nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Sappada e un enclave di lingua tedesca nelle Dolomiti Venete: cucina tirolese autentica.","Gli schlutzkrapfen alle erbe di montagna sono il piatto piu identitario di Sappada.","I knoedel con lo speck del Comelico sono la versione veneta dei canederli: inconfondibili."]},
  {n:"Ristorante Pizzeria Mottolino",a:"Via Livigno 585, Livigno, Lombardia",pl:2,pr:"€€ · ~35€",cu:"Valtellinese Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Pizzeria%20Mottolino%20ristorante",st:"Ristorante sulle piste del Mottolino a Livigno. Cucina livignasca di montagna: pizzoccheri, polenta, selvaggina e Sforzato di Valtellina. Vista panoramica sulle Alpi Retiche.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Sulle piste del Mottolino a 2000 metri: si mangia con le Alpi Retiche intorno.","I pizzoccheri di Livigno con il Casera di Valtellina sono quelli della tradizione alpina piu alta.","Livigno duty free: prezzi vantaggiosi anche al ristorante rispetto al resto delle Alpi."]},
  {n:"Ristorante Re Laurin",a:"Loc. Sella Ronda, Corvara in Badia, Veneto",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Dolomitica",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Re%20Laurin%20ristorante",st:"Ristorante sull Alta Badia con vista sulle Dolomiti patrimonio UNESCO. Cucina dolomitica contemporanea: selvaggina, funghi, erbe di montagna e formaggi d alpeggio della Ladinia.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La Sella Ronda con le Dolomiti intorno e il panorama sciistico piu bello del mondo.","La cucina ladina contemporanea con gli ingredienti dell Alta Badia e di grande identita.","In estate i fiori di montagna e in inverno la neve: le Dolomiti come sfondo sempre diverso."]},
  {n:"Ristorante Salon",a:"Via Nazionale 4, Sauris, Friuli",pl:2,pr:"€€ · ~38€",cu:"Saurana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Salon%20ristorante",st:"Ristorante nel borgo di Sauris a 1400 metri, l unico paese di lingua tedesca del Friuli. Cucina saurana: prosciutto di Sauris IGP, crauti, speck e formaggi delle Carnie.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Sauris e un enclave di lingua tedesca a 1400 metri in Friuli: cucina rara e autentica.","Il prosciutto di Sauris IGP affumicato e uno dei salumi piu pregiati e originali d Italia.","Il borgo di Sauris con il suo lago e uno dei luoghi piu magici delle Alpi italiane."]},
  {n:"Rododendro",a:"Via Badile 4, Valmalenco, Lombardia",pl:3,pr:"€€€ · ~58€",cu:"Malenco di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Rododendro%20ristorante",st:"Ristorante in Valmalenco, la valle del serpentino verde. Cucina valtellinese di montagna: pizzoccheri, bresaola, funghi e Chiscioi, le frittelle di grano saraceno.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La Valmalenco e la valle del serpentino verde: paesaggi alpini di grande purezza.","I Chiscioi di grano saraceno sono il piatto piu identitario della cucina della Valmalenco.","La vista sul Disgrazia e il Bernina durante il pasto vale il viaggio fino in Valmalenco."]},
  {n:"Scrigno del Duomo",a:"Piazza del Duomo 29, Trento, Trentino",pl:3,pr:"€€€ · ~65€",cu:"Trentina Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Scrigno%20del%20Duomo%20ristorante",st:"Ristorante nel centro storico di Trento in Piazza del Duomo. Cucina trentina di qualita: canederli, strangolapreti, capriolo e vini del Trentino. Il ristorante di riferimento del capoluogo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Piazza del Duomo di Trento e una delle piu belle d Italia: cenarvi sotto e un privilegio.","La cucina trentina di qualita nel capoluogo: canederli, strangolapreti e Teroldego nel bicchiere.","Il ristorante di riferimento dei trentini per le occasioni speciali."]},
  {n:"Sissi",a:"Via Galilei 44, Merano, Trentino",pl:4,pr:"€€€€ · ~110€",cu:"Alta Cucina Altoatesina",tg:"italiana",ws:"https://www.google.com/search?q=Sissi%20ristorante",st:"Una stella Michelin a Merano. Chef Andrea Fenoglio. Cucina altoatesina creativa nella citta dell imperatrice Sissi. Ingredienti del Burgraviato: speck, mele, formaggi e selvaggina.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Merano e la citta piu elegante del Trentino-Alto Adige: Sissi ne e il ristorante stellato di riferimento.","Andrea Fenoglio usa gli ingredienti del Burgraviato con una tecnica contemporanea e personale.","La combinazione di cucina altoatesina e terme di Merano e la vacanza gourmet perfetta."]},
  {n:"Stube Gourmet",a:"Via Pecei 6, Asiago, Veneto",pl:4,pr:"€€€€ · ~100€",cu:"Alta Cucina Vicentina",tg:"italiana",ws:"https://www.google.com/search?q=Stube%20Gourmet%20ristorante",st:"Ristorante gourmet sull Altopiano di Asiago. Chef Alessandro Dal Degan. Cucina vicentina di ricerca con ingredienti dell Altopiano: Asiago DOP, funghi, capriolo e bacche selvatiche.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["L Altopiano di Asiago e uno dei piu belli e intatti delle Alpi italiane: la cucina ne riflette l identita.","Alessandro Dal Degan usa l Asiago DOP, i funghi e il capriolo con tecnica contemporanea.","Una stella Michelin sull altopiano che ospito la Grande Guerra: cucina e storia unite."]},
  {n:"Stube Hermitage",a:"Via Castelletto Inferiore 69, Madonna di Campiglio, Trentino",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Stube%20Hermitage%20ristorante",st:"Una stella Michelin al Bio Hotel Hermitage di Madonna di Campiglio. Cucina alpina biologica con ingredienti del territorio trentino. La sostenibilita come valore fondante.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Il Bio Hotel Hermitage porta la cucina biologica d alpeggio a livelli di grande raffinatezza.","La vista sulle Dolomiti di Brenta durante la cena e una delle esperienze piu emozionanti d Italia.","Cucina alpina sostenibile: ogni ingrediente e tracciato e coltivato nel rispetto della montagna."]},
  {n:"Terra",a:"Via Prati 1, San Genesio Atesino, Trentino",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Alpina",tg:"italiana",ws:"https://www.google.com/search?q=Terra%20ristorante",st:"Due stelle Michelin in Val Sarentino. Chef Heinrich Schneider. Cucina alpina di grande profondita: ingredienti della val Sarentino, formaggi, erbe e selvaggina delle Alpi.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin per una cucina alpina che non ha nulla da invidiare alla grande cucina francese.","La val Sarentino e il territorio piu autentico del Trentino-Alto Adige: Schneider lo racconta bene.","Il cervo marinato con bacche di ginepro e uno dei piatti piu emozionanti della cucina alpina."]},
  {n:"Tivoli",a:"Via Lacedel 34, Cortina d'Ampezzo, Veneto",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Ampezzana",tg:"italiana",ws:"https://www.google.com/search?q=Tivoli%20ristorante",st:"Una stella Michelin a Cortina d Ampezzo. Chef Graziano Prest. Il ristorante stellato piu elegante di Cortina: cucina italiana d autore con ingredienti ampezzani in una villa dei primi del 900.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Il ristorante stellato di Cortina: nella citta olimpica delle Dolomiti la cucina e all altezza.","Graziano Prest porta una cucina italiana raffinata con ingredienti della valle ampezzana.","La villa dei primi del 900 a Cortina e la location storica piu elegante delle Dolomiti."]},
  {n:"Trattoria al Fogolar",a:"Via Carnia 12, Forni di Sopra, Friuli",pl:2,pr:"€€ · ~35€",cu:"Carnica di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20al%20Fogolar%20ristorante",st:"Trattoria a Forni di Sopra in Carnia. Cucina carnica della tradizione: cjarsons dolce-salati, polenta di Carnia, frico croccante. La cucina di montagna friulana nella sua versione piu autentica.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I cjarsons di Forni di Sopra sono i piu elaborati del Friuli: ricetta antica con 30 ingredienti.","La Carnia e la zona di montagna piu autentica del Friuli: cucina conservata nei secoli.","Il frico croccante con la polenta di Carnia e il piatto piu iconico della montagna friulana."]},
  {n:"Trattoria Al Grop",a:"Via Tarcento 40, Nimis, Friuli",pl:2,pr:"€€ · ~35€",cu:"Friulana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20Al%20Grop%20ristorante",st:"Trattoria storica a Nimis nelle Prealpi Friulane. Cucina friulana autentica: frico croccante, cjarsons della Val Pusteria, musetto con brovada. I sapori piu autentici del Friuli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Il frico croccante di Nimis e quello originale della tradizione friulana: formaggio e patate, null altro.","I cjarsons sono i ravioli dolce-salati del Friuli: un piatto che non esiste in nessun altro posto.","Le Prealpi Friulane intorno a Nimis producono i vini e i formaggi piu identitari della regione."]},
  {n:"Trattoria da Fausto",a:"Via Provinciale 12, Ligonchio, Emilia Romagna",pl:1,pr:"€ · ~25€",cu:"Reggiana di Montagna",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20da%20Fausto%20ristorante",st:"Trattoria storica a Ligonchio nell Appennino reggiano, paese natale di Miriam Makeba. Cucina di montagna reggiana: gnocco fritto, erbazzone, cinghiale con polenta.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Ligonchio e il paese dove Miriam Makeba visse in esilio: cucina e storia si intrecciano.","Il cinghiale con la polenta dell Appennino reggiano e il piatto piu sostanzioso della montagna.","L erbazzone reggiano con le erbette selvatiche qui e in versione montana: piu intensa e profumata."]},
  {n:"Trattoria del Tonno",a:"Via Nazionale 4, Caspoggio, Lombardia",pl:2,pr:"€€ · ~36€",cu:"Valmalenco Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20del%20Tonno%20ristorante",st:"Trattoria storica in Valmalenco a Caspoggio. Cucina della Valmalenco: pizzoccheri, polenta con il Casera, sciatt e funghi porcini della valle. La tradizione di malga nel piatto.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Caspoggio e il paese piu soleggiato della Valmalenco: cucina di tradizione autentica.","I pizzoccheri con il Casera stagionato sono quelli della ricetta originale valtellinese.","I funghi porcini della Valmalenco crescono in uno dei boschi piu ricchi delle Alpi."]},
  {n:"Tre Cristi",a:"Via Carducci 12, Sondrio, Lombardia",pl:3,pr:"€€€ · ~60€",cu:"Valtellinese Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Tre%20Cristi%20ristorante",st:"Ristorante contemporaneo a Sondrio. Cucina valtellinese rivisitata con ingredienti di eccellenza: bresaola, Casera, funghi porcini delle Orobie. Cantina con Nebbiolo di Valtellina.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La cucina valtellinese contemporanea di Tre Cristi trova un equilibrio tra tradizione e creativita.","La cantina con il Sassella, il Grumello e il Valgella e un viaggio nel Nebbiolo di montagna.","Il capoluogo della Valtellina ha finalmente il suo indirizzo gastronomico di qualita."]},
  {n:"Villa Maiella",a:"Via Sette Dolori 30, Guardiagrele, Abruzzo",pl:4,pr:"€€€€ · ~90€",cu:"Alta Cucina Abruzzese",tg:"italiana",ws:"https://www.google.com/search?q=Villa%20Maiella%20ristorante",st:"Una stella Michelin a Guardiagrele ai piedi della Maiella. Chef Arcangelo Tinari. Cucina abruzzese d autore con ingredienti del Parco Nazionale della Maiella: agnello, zafferano di Navelli, tartufo.",mi:{s:1,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:17,l:"17/20"},rv:["La Maiella e il monte piu mistico d Abruzzo: Villa Maiella ne racconta i sapori con grande rispetto.","Lo zafferano di Navelli e il piu pregiato d Italia: qui entra in ogni piatto con intelligenza.","L agnello abruzzese della Maiella e di qualita eccezionale: il pascolo ad alta quota si sente."]},
  {n:"Rifugio Calvi",a:"Loc. Calvi 2215m, Carona, Lombardia",pl:1,pr:"€ · ~22€",cu:"Cucina di Rifugio",tg:"italiana",ws:"https://www.google.com/search?q=Rifugio%20Calvi%20ristorante",st:"Rifugio a 2215 metri nella Val Brembana in Orobie Bergamasche. Cucina di rifugio bergamasca: polenta, formaggi di malga, spezzatino. Vista sul Pizzo del Diavolo.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["A 2215 metri nelle Orobie Bergamasche: il rifugio piu bello della Val Brembana.","La polenta con il Formai de Mut DOP di alpeggio e il pasto piu puro delle Alpi bergamasche.","Il Pizzo del Diavolo come sfondo: cucina e paesaggio si incontrano alla perfezione."]}
];
var favs=new Set(JSON.parse(localStorage.getItem('mofav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('mowish25')||'[]'));
function saveFavs(){localStorage.setItem('mofav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('mowish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false,wish:false};

var mainZones=['trentino','lombardia','piemonte','veneto','friuli','emilia romagna','abruzzo'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Milano');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n);
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.wish&&!wish.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
updateWishCount();
render();
